# Generated by Django 2.2.4 on 2019-10-02 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0003_auto_20190918_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='bb',
            name='image',
            field=models.ImageField(blank=True, help_text='150x150px', null=True, upload_to='images/bboard', verbose_name='Изображение'),
        ),
    ]
