# Generated by Django 2.2.4 on 2019-10-02 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0004_bb_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bb',
            name='image',
        ),
        migrations.AddField(
            model_name='bb',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d'),
        ),
    ]
