# Generated by Django 2.2.4 on 2019-10-04 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0005_auto_20191002_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bb',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m/%d'),
        ),
    ]
