# Generated by Django 2.2.4 on 2019-10-04 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0006_auto_20191004_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bb',
            name='photo',
        ),
        migrations.AddField(
            model_name='bb',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
